### ISSUE TITLE
Allow customization of input/output ports

### ISSUE THREAD

**Issue by aalmiray** [miho/VWorkflows#35]
VWorkflows restricts and optimizes connectors to `Circle` instances.

**Comment by miho** [comment]
Works now via CSS, e.g.:

```css
.vnode-connector {
    -fx-background-color: rgba(0,0,0,0.75);
    -fx-stroke: rgba(120, 140, 255, 0.42);
    -fx-border-width: 2px; 
    -fx-border-color: rgba(120, 140, 255, 0.72);
    -fx-shape: "m 187.92089,378.88528 a 12.94066,12.94066 0 0 1 -12.94067,12.94066 12.94066,12.94066 0 0 1 -12.94066,-12.94066 12.94066,12.94066 0 0 1 12.94066,-12.94066 12.94066,12.94066 0 0 1 12.94067,12.94066 z"
}
```
